/* eslint-disable */
module.exports = [
  "Moi, Adam et Eve, j’y crois plus tu vois parce que je suis pas un idiot: la pomme ça peut pas être mauvais, c’est plein de pectine",
  "Une femme qui est enceinte, par exemple, elle est aware qu‘elle attend un enfant...",
  "Marcel Proust, oui. Un peu comme moi. Longtemps il s'est couché aware.",
  "Quand tu joues au Go.. faut être aware. Si t'es pas aware, tes pierres sont mortes, et toi avec.",
  "La drogue, c'est comme quand tu close your eyes et que tu traverses la rue.",
  "Une noisette, j‘la casse entre mes fesses tu vois",
  "Je crois au moment. S‘il n‘y a pas le moment, à ce moment-là, il faut arriver à ce moment-là, au moment qu‘on veut",
  "Le monde est composé de flèches et de molécules et d'électricité comme le Big-Bang tu vois, et tout ça ensemble ça forme l'Univers",
  "Quand j'étais jeune j'étais très con. Je suis resté très jeune.",
  "Le talent, ça se travaille, mais ça ne se perd pas.",
  "Si tu dis couic-couic quand tu marches, les gens pensent que t'as des chaussures neuves.",
  "Un bon truc pour paraître dix ans plus jeune, c'est de te vieillir de dix ans quand tu dis ton âge.",
  "Van Damme is back, physically and mentally. Y a rien qui peut me stopper, except... myself and god.",
  "Si tu invites des gens qui ont tous le même groupe sanguin à une fête, mais que tu le leur dis pas, ils vont parler d'autre chose",
  "Dans les magasins de lingerie, on ne voit pas de calendriers avec des photos de garage.",
  "Si tu travailles avec un marteau-piqueur pendant un tremblement de terre, désynchronise-toi, sinon tu travailles pour rien.",
  "Le ridicule n'existe pas, on crée le ridicule.",
  "Si tu téléphones à une voyante et qu'elle ne décroche pas avant que ça sonne, raccroche.",
  "Le grand combat, c'est contre soi-même. La victoire, c'est d'avoir compris ce que l'on veut... et d'y croire.",
  "Le rêve, it's a feeling, c'est une sensation, une sensation réelle qui se produit si on veut.",
  "Si tu parles à ton eau de Javel pendant que tu fais la vaisselle, elle est moins concentrée.",
  "L'air tu peux pas le toucher... ça existe et ça existe pas... Ca nourrit l'homme sans qu'il ait faim.",
  "Quand tu prends confiance en la confiance, tu deviens confiant.",
  "Un biscuit ça n'a pas de spirit c'est juste un biscuit mais avant c'était du lait,des œufs et dans les œufs il y a la vie potentielle",
  "J'adore l'eau. Dans 20-30 ans, y'en aura plus.",
  "Il y avait tout dans Tintin... Bob Morane c'est Tintin en un peut plus profond.",
  "L'air est fait d'oxygène CO2",
  "Si tu dors et que tu rêves que tu dors, il faut que tu te réveilles deux fois pour te lever.",
  "T'as pas besoin d'un flash quand tu photographies un lapin qui a déjà les yeux rouges.",
  // "Nous les humains, on a inventé le temps. Mais le temps n‘existe pas, car il y a une matter, une puissance de compression, qui n‘est pas la même pour chaque species on earth.",
  // "Selon les statistiques, il y a une personne sur cinq qui est déséquilibrée. S'il y a 4 personnes autour de toi et qu'elles te semblent normales, c'est pas bon.",
  // "Mes autres prénoms sont Camille et François. J'aime bien Camille non? Ça fait old fashion tu trouves pas? Ça respire le meuble de Provence",
  // "Quand on sort d'un placenta à l'age de 42 ans et quand on a l'intelligence, le brain, le computer, la mémoire d'un 40 ans mais qui est vide, elle doit se remplir de jour en jour, elle doit sponging, elle doit elle doit prendre comme une éponge, elle doit elle doit... ok ?",
  // "L'être humain, en général, dans la vie, réacte. On réacte, c'est à dire qu'on fait ce qu'on est supposé faire. Travailler, manger... J'm'excuse de l'expression; chier, mais je trouve qu'un être humain doit créer.",
  // "Une vache, ça te bouffe trois hectares, moi avec trois hectares, je te fais deux mille kilos de riz. Avec trois hectares, je te nourris Avignon tu vois",
  // "Les plantes par exemple, qui n'ont pas de mains, et pas d'oreilles, elles sentent les choses, les vibrations, elles sont plus aware que les autres species",
];
